# Generated by Django 3.1.2 on 2020-12-13 03:08

from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_auto_20201213_0258'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faqconfiguration',
            options={'verbose_name': 'Konfiguracja pytan', 'verbose_name_plural': 'Konfiguracja pytan'},
        ),
        migrations.AlterModelOptions(
            name='faqitem',
            options={'verbose_name': 'Pytanie i odpowiedz (faq)', 'verbose_name_plural': 'Pytania i odpowiedzi (faqs)'},
        ),
        migrations.AlterField(
            model_name='faqconfiguration',
            name='main_image',
            field=models.ImageField(upload_to='images/', verbose_name='Glowny obrazek'),
        ),
        migrations.AlterField(
            model_name='faqconfiguration',
            name='main_image_alt',
            field=models.CharField(max_length=200, verbose_name='Nazwa'),
        ),
        migrations.AlterField(
            model_name='faqconfiguration',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Data modyfikacji'),
        ),
        migrations.AlterField(
            model_name='faqitem',
            name='answer_text',
            field=djrichtextfield.models.RichTextField(verbose_name='Tresc odpowiedzi'),
        ),
        migrations.AlterField(
            model_name='faqitem',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Kolejnosc'),
        ),
        migrations.AlterField(
            model_name='faqitem',
            name='question_text',
            field=djrichtextfield.models.RichTextField(verbose_name='Tresc pytania'),
        ),
        migrations.AlterField(
            model_name='faqitem',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji'),
        ),
    ]
