# Generated by Django 3.1.5 on 2021-02-25 19:17

from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PromoClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, verbose_name='Adres email')),
                ('contact_name', models.CharField(blank=True, max_length=100, verbose_name='Imie i nazwisko osoby kontaktowej')),
                ('company_name', models.CharField(blank=True, max_length=100, verbose_name='Nazwa firmy')),
                ('postcode', models.TextField(blank=True, max_length=6, verbose_name='Kod pocztowy')),
                ('street', models.TextField(blank=True, max_length=100, verbose_name='Ulica i numer')),
                ('city', models.TextField(blank=True, max_length=100, verbose_name='Miasto')),
                ('phone', models.TextField(max_length=20, verbose_name='Telefon')),
                ('inpost_code', models.CharField(blank=True, max_length=20, verbose_name='Kod InPost')),
                ('delivery_place', models.CharField(blank=True, max_length=100, verbose_name='Miejsce InPost (alternatywa dla kodu)')),
                ('permission', models.BooleanField(blank=True, default=False, verbose_name='Czy klient wyrazil konieczna zgode?')),
                ('nip', models.CharField(blank=True, max_length=30, verbose_name='Numer NIP')),
                ('is_vat', models.BooleanField(verbose_name='Czy faktura VAT? Czy to firma?')),
                ('delivery_kind', models.CharField(choices=[('KURIER', 'KURIER'), ('INPOST', 'INPOST')], max_length=30, verbose_name='Czy kurier czy paczkomat?')),
            ],
        ),
        migrations.CreateModel(
            name='PromoConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_text', djrichtextfield.models.RichTextField(default='Oświadczam, że wyrażam zgodę na przetwarzanie i wykorzystanie moich danych osobowych w celu realizacji zamówienia przez Justyna Pietraszek Mobilne Centrum Masażu Relaksownia, ul. Świętej Bronisławy 13/5, 44-100 Gliwice, NIP: 9691217183, REGON: 383441026, który jest administratorem danych osobowych zgodnie z przepisami Rozporządzenia Parlamentu Europejskiego i Rady (UE) 2016/679 z dnia 27 kwietnia 2016 r. w sprawie ochrony osób fizycznych w związku z przetwarzaniem danych osobowych i w sprawie swobodnego przepływu takich danych oraz uchylenia dyrektywy 95/46/WE i ustawy o ochronie danych osobowych z dnia 10 maja 2018 r. (Dz.U. 2018 poz. 1000)', verbose_name='Treść zgody przy formularzu zamówienia')),
                ('delivery_info', djrichtextfield.models.RichTextField(default='Książka będzie wysłana i doręczona za pomocą paczkomatu lub kuriera Inpost. W przypadku wyboru paczkomatu do ceny trzeba doliczyć 13 zł, w przypadku kuriera 16,50 zł. Wysyłka zamówienia będzie realizowana tylko na terenie Polski', verbose_name='Treść zgody przy formularzu zamówienia')),
                ('bank_account_number', models.CharField(default='00 0000 0000 0000 0000 0000 0000', max_length=6, verbose_name='Numer konta bankowego')),
            ],
        ),
        migrations.CreateModel(
            name='PromoPageComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='images/', verbose_name='Glowny obrazek')),
                ('photo_alt', models.CharField(max_length=100, verbose_name='Nazwa')),
                ('photo_responsive1', models.ImageField(upload_to='images/', verbose_name='Kawalek 1 - do wersji responsywnej')),
                ('photo_responsive1_alt', models.CharField(max_length=100, verbose_name='Nazwa 1')),
                ('photo_responsive2', models.ImageField(upload_to='images/', verbose_name='Kawalek 2 - do wersji responsywnej')),
                ('photo_responsive2_alt', models.CharField(max_length=100, verbose_name='Nazwa 2')),
                ('photo_responsive3', models.ImageField(blank=True, upload_to='images/', verbose_name='Kawalek 3 - do wersji responsywnej')),
                ('photo_responsive3_alt', models.CharField(blank=True, max_length=100, verbose_name='Nazwa 3')),
                ('photo_responsive4', models.ImageField(blank=True, upload_to='images/', verbose_name='Kawalek 4 - do wersji responsywnej')),
                ('photo_responsive4_alt', models.CharField(blank=True, max_length=100, verbose_name='Nazwa 4')),
                ('text', djrichtextfield.models.RichTextField(blank=True, verbose_name='Tekst')),
                ('text_position', models.IntegerField(default=1, verbose_name='Pozycja tekstu, jeśli jest jakiś ustawiony 1 - przed obrazkami, 2+ po obrazkach')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Data modyfikacji')),
                ('element_order', models.IntegerField(default=0, verbose_name='Kolejnosc')),
            ],
            options={
                'verbose_name': 'Element strony promocji',
                'verbose_name_plural': 'Elementy strony promocji',
            },
        ),
    ]
