# Generated by Django 3.1.5 on 2021-01-29 20:03

from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PromoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='images/', verbose_name='Glowny obrazek')),
                ('photo_alt', models.CharField(max_length=200, verbose_name='Nazwa')),
                ('photo_responsive1', models.ImageField(upload_to='images/', verbose_name='Czesc pierwsza obrazka - do wersji responsywnej')),
                ('photo_responsive1_alt', models.CharField(max_length=200, verbose_name='Nazwa p1')),
                ('photo_responsive2', models.ImageField(upload_to='images/', verbose_name='Czesc druga obrazka - do wersji responsywnej')),
                ('photo_responsive2_alt', models.CharField(max_length=200, verbose_name='Nazwa p2')),
                ('text', djrichtextfield.models.RichTextField(blank=True, verbose_name='Tekst')),
                ('text_position', models.IntegerField(default=1, verbose_name='Pozycja tekstu, jeśli jest jakiś ustawiony (1 - przed obrazkiem, 2 - po pierwszym obrazku, 3 - po drugim obrazku')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Data modyfikacji')),
                ('element_order', models.IntegerField(default=0, verbose_name='Kolejnosc')),
            ],
            options={
                'verbose_name': 'Element strony promocji',
                'verbose_name_plural': 'Elementy strony promocji',
            },
        ),
    ]
