# Generated by Django 3.1.5 on 2021-03-01 16:58

from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promoconfiguration',
            name='bank_account_number',
            field=models.CharField(default='00000000000000000000000000', max_length=26, verbose_name='Numer konta bankowego'),
        ),
        migrations.AlterField(
            model_name='promoconfiguration',
            name='delivery_info',
            field=djrichtextfield.models.RichTextField(default='Książka będzie wysłana i doręczona za pomocą paczkomatu lub kuriera Inpost. W przypadku wyboru paczkomatu do ceny trzeba doliczyć 13 zł, w przypadku kuriera 16,50 zł. Wysyłka zamówienia będzie realizowana tylko na terenie Polski', verbose_name='Informacja o dostawie'),
        ),
    ]
