# Generated by Django 3.1.5 on 2021-01-30 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promoitem',
            name='photo_responsive3',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='Kawalek 3 - do wersji responsywnej'),
        ),
        migrations.AddField(
            model_name='promoitem',
            name='photo_responsive3_alt',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nazwa 3'),
        ),
        migrations.AddField(
            model_name='promoitem',
            name='photo_responsive4',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='Kawalek 4 - do wersji responsywnej'),
        ),
        migrations.AddField(
            model_name='promoitem',
            name='photo_responsive4_alt',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nazwa 4'),
        ),
        migrations.AlterField(
            model_name='promoitem',
            name='photo_responsive1',
            field=models.ImageField(upload_to='images/', verbose_name='Kawalek 1 - do wersji responsywnej'),
        ),
        migrations.AlterField(
            model_name='promoitem',
            name='photo_responsive1_alt',
            field=models.CharField(max_length=200, verbose_name='Nazwa 1'),
        ),
        migrations.AlterField(
            model_name='promoitem',
            name='photo_responsive2',
            field=models.ImageField(upload_to='images/', verbose_name='Kawalek 2 - do wersji responsywnej'),
        ),
        migrations.AlterField(
            model_name='promoitem',
            name='photo_responsive2_alt',
            field=models.CharField(max_length=200, verbose_name='Nazwa 2'),
        ),
        migrations.AlterField(
            model_name='promoitem',
            name='text_position',
            field=models.IntegerField(default=1, verbose_name='Pozycja tekstu, jeśli jest jakiś ustawiony 1 - przed obrazkami, 2+ po obrazkach'),
        ),
    ]
