# Generated by Django 3.1.5 on 2021-03-02 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0003_promoconfiguration_inpost_code_search_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promoconfiguration',
            name='inpost_code_search_info',
            field=models.CharField(default='https://inpost.pl/znajdz-paczkomat', max_length=100, verbose_name='Link do wyszukiwarki paczkomatow INPOST'),
        ),
    ]
