# Generated by Django 3.1.5 on 2021-03-04 16:53

from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0004_auto_20210302_2256'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoEmailConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', djrichtextfield.models.RichTextField(default='Twoje zamówienie zostało przyjęte.', verbose_name='Temat wiadomosci')),
                ('message', djrichtextfield.models.RichTextField(default='Dziękuję za zainteresowanie książką Doskonale Niedoskonali i złożenie zamówienia. Twoje zamówienie zostało przyjęte i zostanie realizowane jak tylko płatność zostanie potwierdzona. W dniu wysyłki zostaniesz o tym poinformowany drogą mailową i otrzymasz informacje zawierające: ', verbose_name='Tresc wiadomosci')),
                ('from_email', djrichtextfield.models.RichTextField(default='kontakt@relaksownia.org.pl', verbose_name='Od kogo?')),
            ],
        ),
        migrations.AlterField(
            model_name='promoclient',
            name='delivery_kind',
            field=models.CharField(choices=[('KURIER', 'Dostawa kurierem'), ('INPOST', 'Dostawa do paczkomatu InPOST')], default='INPOST', max_length=30, verbose_name='Czy kurier czy paczkomat?'),
        ),
    ]
