# Generated by Django 3.1.5 on 2021-03-04 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0006_auto_20210304_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promoemailconfiguration',
            name='subject',
            field=models.CharField(default='Twoje zamówienie zostało przyjęte.', max_length=200, verbose_name='Temat wiadomosci'),
        ),
    ]
