# Generated by Django 3.2 on 2021-04-21 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0008_promoemailconfiguration_admin_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promoconfiguration',
            name='permission_text',
            field=models.TextField(default='Oświadczam, że wyrażam zgodę na przetwarzanie i wykorzystanie moich danych osobowych w celu realizacji zamówienia przez Justyna Pietraszek Mobilne Centrum Masażu Relaksownia, ul. Świętej Bronisławy 13/5, 44-100 Gliwice, NIP: 9691217183, REGON: 383441026, który jest administratorem danych osobowych zgodnie z przepisami Rozporządzenia Parlamentu Europejskiego i Rady (UE) 2016/679 z dnia 27 kwietnia 2016 r. w sprawie ochrony osób fizycznych w związku z przetwarzaniem danych osobowych i w sprawie swobodnego przepływu takich danych oraz uchylenia dyrektywy 95/46/WE i ustawy o ochronie danych osobowych z dnia 10 maja 2018 r. (Dz.U. 2018 poz. 1000)', verbose_name='Treść zgody przy formularzu zamówienia'),
        ),
    ]
