# Generated by Django 3.1.2 on 2020-11-23 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offeritem',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
