# Generated by Django 3.2 on 2021-05-15 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0002_offerconfiguration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offerconfiguration',
            options={'verbose_name': 'Oferta - konfiguracja', 'verbose_name_plural': 'Oferta - konfiguracja'},
        ),
    ]
