# Generated by Django 3.1.2 on 2020-12-13 03:08

from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0003_auto_20201213_0258'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OfferConfiguration',
        ),
        migrations.AlterModelOptions(
            name='offeritem',
            options={'verbose_name': 'Oferta', 'verbose_name_plural': 'Lista ofert'},
        ),
        migrations.AlterField(
            model_name='offeritem',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='Obrazek'),
        ),
        migrations.AlterField(
            model_name='offeritem',
            name='image_alt',
            field=models.TextField(verbose_name='Nazwa'),
        ),
        migrations.AlterField(
            model_name='offeritem',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Kolejnosc'),
        ),
        migrations.AlterField(
            model_name='offeritem',
            name='text',
            field=djrichtextfield.models.RichTextField(verbose_name='Tresc'),
        ),
        migrations.AlterField(
            model_name='offeritem',
            name='title',
            field=models.TextField(verbose_name='Tytul'),
        ),
        migrations.AlterField(
            model_name='offeritem',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Data modyfikacji'),
        ),
    ]
