# Generated by Django 3.1.2 on 2020-10-20 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email klienta', max_length=300)),
                ('name', models.CharField(help_text='Imie klienta', max_length=400)),
                ('permission', models.BooleanField(help_text='Zgoda na marketing klienta')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='modification date')),
            ],
        ),
    ]
