# Generated by Django 3.1.2 on 2020-12-13 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=300, verbose_name='Email klienta')),
                ('name', models.CharField(max_length=400, verbose_name='Imie klienta')),
                ('permission', models.BooleanField(verbose_name='Zgoda na marketing')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Data modyfikacji')),
            ],
            options={
                'verbose_name': 'Klient',
                'verbose_name_plural': 'Dane klientow zapisanych na newsletter',
            },
        ),
    ]
