# Generated by Django 3.1.2 on 2020-12-13 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'verbose_name': 'Klient', 'verbose_name_plural': 'Dane klientow zapisanych na newsletter'},
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='email',
            field=models.EmailField(max_length=300, verbose_name='Email klienta'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='name',
            field=models.CharField(max_length=400, verbose_name='Imie klienta'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='permission',
            field=models.BooleanField(verbose_name='Zgoda na marketing'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Data modyfikacji'),
        ),
    ]
