# Generated by Django 3.2 on 2021-05-14 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opinions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinionsconfiguration',
            name='tree_header',
            field=models.TextField(default='Dlaczego nasza oferta jest taka wyjątkowa?', verbose_name='Tekst nad drzewkiem'),
        ),
    ]
