# Generated by Django 3.2 on 2021-10-29 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opinions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinionitem',
            name='image',
            field=models.ImageField(default='', upload_to='images/', verbose_name='Zdjecie miniaturka osoby'),
        ),
        migrations.AddField(
            model_name='opinionitem',
            name='image_alt',
            field=models.CharField(default='', max_length=200, verbose_name='Tekst gdy zdjecie sie nie zaladuje'),
        ),
        migrations.AddField(
            model_name='opinionitem',
            name='stars',
            field=models.IntegerField(default=5, max_length=1, verbose_name='Ocena, ilosc gwiazdek'),
        ),
    ]
