# Generated by Django 3.2 on 2021-10-29 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opinions', '0002_auto_20211029_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinionitem',
            name='stars',
            field=models.IntegerField(default=5, verbose_name='Ocena, ilosc gwiazdek'),
        ),
    ]
