# Generated by Django 3.1.2 on 2020-10-17 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opinions', '0002_opiniontreeitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opiniontreeitem',
            name='img',
            field=models.ImageField(help_text='Ilustracja wyswietlana w drzewku na podstronie opinii', upload_to='images/'),
        ),
    ]
