# Generated by Django 3.1.2 on 2020-12-13 03:08

from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('opinions', '0002_auto_20201213_0258'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opinionitem',
            options={'verbose_name': 'OpinionItem'},
        ),
        migrations.AlterModelOptions(
            name='opinionsconfiguration',
            options={'verbose_name': 'OpinionsConfiguration'},
        ),
        migrations.AlterModelOptions(
            name='opiniontreeitem',
            options={'verbose_name': 'OpinionTreeItem'},
        ),
        migrations.AlterField(
            model_name='opinionitem',
            name='customer_name',
            field=models.CharField(max_length=400, verbose_name='Imie osoby polecajacej'),
        ),
        migrations.AlterField(
            model_name='opinionitem',
            name='opinion_text',
            field=djrichtextfield.models.RichTextField(verbose_name='Tekst rekomendacji'),
        ),
        migrations.AlterField(
            model_name='opinionitem',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Kolejnosc'),
        ),
        migrations.AlterField(
            model_name='opinionitem',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Data modyfikacji'),
        ),
        migrations.AlterField(
            model_name='opinionsconfiguration',
            name='main_image',
            field=models.ImageField(upload_to='images/', verbose_name='Obrazek wyswietlany na gorze strony pod menu'),
        ),
        migrations.AlterField(
            model_name='opinionsconfiguration',
            name='main_image_alt',
            field=models.CharField(max_length=200, verbose_name='Nazwa'),
        ),
        migrations.AlterField(
            model_name='opinionsconfiguration',
            name='tree_img',
            field=models.ImageField(upload_to='images/', verbose_name='Obrazek wyswietlany jako glowny w drzewku'),
        ),
        migrations.AlterField(
            model_name='opinionsconfiguration',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Data modyfikacji'),
        ),
        migrations.AlterField(
            model_name='opiniontreeitem',
            name='img',
            field=models.ImageField(upload_to='images/', verbose_name='Ilustracja wyswietlana w drzewku na podstronie opinii'),
        ),
        migrations.AlterField(
            model_name='opiniontreeitem',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Kolejnosc'),
        ),
        migrations.AlterField(
            model_name='opiniontreeitem',
            name='text',
            field=djrichtextfield.models.RichTextField(verbose_name='Tekst wyswietlany w drzewku na podstronie opinii'),
        ),
    ]
