# Generated by Django 3.1.2 on 2020-12-13 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opinions', '0003_auto_20201213_0408'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opinionitem',
            options={'verbose_name': 'Opinia', 'verbose_name_plural': 'Opinie'},
        ),
        migrations.AlterModelOptions(
            name='opinionsconfiguration',
            options={'verbose_name': 'Konfiguracja opinii', 'verbose_name_plural': 'Konfiguracja opinii'},
        ),
        migrations.AlterModelOptions(
            name='opiniontreeitem',
            options={'verbose_name': 'Element drzewka na stronie opinii', 'verbose_name_plural': 'Elementy drzewka na stronie opinie'},
        ),
    ]
