# Generated by Django 3.1.2 on 2020-10-17 23:05

from django.db import migrations, models
import djrichtextfield.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', djrichtextfield.models.RichTextField()),
                ('email', models.EmailField(help_text='Email klienta', max_length=300)),
                ('phone', models.CharField(help_text='Telefon klienta', max_length=400)),
                ('name', models.CharField(help_text='Imie klienta', max_length=400)),
                ('attachment_img', models.ImageField(help_text='Klient moze zalaczyc obrazek, screen', max_length=400, upload_to='images/')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='modification date')),
            ],
        ),
        migrations.CreateModel(
            name='ContactConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_url', models.CharField(help_text='Url (adres) do mapy google', max_length=400)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(max_length=254)),
                ('on_site_client_info', djrichtextfield.models.RichTextField(default='', help_text='Informacja o tym, ze dojezdzasz do klienta')),
                ('have_questions', djrichtextfield.models.RichTextField(default='', help_text='Informacja nad formularzem "czy masz pytania?"')),
                ('working_hours', djrichtextfield.models.RichTextField(help_text='Godziny pracy')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='modification date')),
            ],
        ),
    ]
