# Generated by Django 3.1.2 on 2020-12-13 20:50

from django.db import migrations, models
import djrichtextfield.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=2000, verbose_name='Wiadomosc od klienta')),
                ('email', models.EmailField(blank=True, max_length=300, verbose_name='Email klienta')),
                ('phone', models.CharField(blank=True, max_length=400, verbose_name='Telefon klienta')),
                ('name', models.CharField(max_length=400, verbose_name='Imie klienta')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Data modyfikacji')),
            ],
            options={
                'verbose_name': 'Zapisany kontakt do klienta',
                'verbose_name_plural': 'Dane klientow',
            },
        ),
        migrations.CreateModel(
            name='ContactConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_url', models.CharField(max_length=350, verbose_name='Url (adres) do mapy google')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(help_text='Bedzie on wyswietlany zarowno na stronie kontakt jak i w stopce', max_length=128, region=None, verbose_name='Twoj numer telefonu')),
                ('email', models.EmailField(max_length=254, verbose_name='Twoj email')),
                ('on_site_client_info', djrichtextfield.models.RichTextField(default='', verbose_name='Informacja o tym, ze dojezdzasz do klienta')),
                ('have_questions', djrichtextfield.models.RichTextField(default='', verbose_name='Informacja nad formularzem "czy masz pytania?"')),
                ('working_hours', djrichtextfield.models.RichTextField(verbose_name='Godziny pracy')),
                ('facebook', models.CharField(blank=True, default='', max_length=200, verbose_name='Url (adres) do facebooka')),
                ('twitter', models.CharField(blank=True, default='', max_length=200, verbose_name='Url (adres) do twittera')),
                ('linkedin', models.CharField(blank=True, default='', max_length=200, verbose_name='Url (adres) do LinkedIn')),
                ('instagram', models.CharField(blank=True, default='', max_length=200, verbose_name='Url (adres) do Instagrama')),
                ('snapchat', models.CharField(blank=True, default='', max_length=200, verbose_name='Url (adres) do Snapchat')),
                ('youtube', models.CharField(blank=True, default='', max_length=200, verbose_name='Url (adres) do YouTube')),
                ('google_plus', models.CharField(blank=True, default='', max_length=200, verbose_name='Url (adres) do Google+')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Data modyfikacji')),
            ],
            options={
                'verbose_name': 'Konfiguracja strony kontakt i informacji kontaktowych',
                'verbose_name_plural': 'Konfiguracja strony kontakt i informacji kontaktowych',
            },
        ),
    ]
