# Generated by Django 3.1.2 on 2020-10-10 17:08

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactconfiguration',
            name='have_questions',
            field=djrichtextfield.models.RichTextField(default='', help_text='Informacja nad formularzem "czy masz pytania?"'),
            preserve_default=False,
        ),
    ]
