# Generated by Django 3.1.2 on 2020-10-20 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='attachment_img',
            field=models.ImageField(blank=True, help_text='Klient moze zalaczyc obrazek, screen', max_length=400, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(help_text='Wiadomość od klienta', max_length=2000),
        ),
    ]
