# Generated by Django 3.1.2 on 2020-10-10 17:25

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contactconfiguration_have_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactconfiguration',
            name='have_questions',
            field=djrichtextfield.models.RichTextField(default='', help_text='Informacja nad formularzem "czy masz pytania?"'),
        ),
        migrations.AlterField(
            model_name='contactconfiguration',
            name='on_site_client_info',
            field=djrichtextfield.models.RichTextField(default='', help_text='Informacja o tym, ze dojezdzasz do klienta'),
        ),
    ]
