# Generated by Django 3.1.2 on 2020-12-27 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20201227_0427'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='permission',
            field=models.BooleanField(default=True, verbose_name='Zgoda na kontakt'),
            preserve_default=False,
        ),
    ]
