# Generated by Django 3.1.5 on 2021-01-28 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_contact_permission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactconfiguration',
            old_name='google_plus',
            new_name='google_map',
        ),
    ]
