# Generated by Django 3.1.2 on 2020-10-16 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20201010_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='attachment_img',
            field=models.ImageField(help_text='Klient moze zalaczyc obrazek, screen', max_length=400, upload_to='images/'),
        ),
    ]
