# Generated by Django 3.1.2 on 2020-11-23 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20201112_0353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='attachment_img',
        ),
    ]
