# Generated by Django 3.1.2 on 2020-12-12 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_auto_20201212_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactconfiguration',
            name='map_url',
            field=models.CharField(help_text='Url (adres) do mapy google', max_length=350),
        ),
    ]
