# Generated by Django 3.1.2 on 2020-12-12 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_auto_20201212_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactconfiguration',
            name='facebook',
            field=models.CharField(blank=True, default='', help_text='Url (adres) do facebooka', max_length=200),
        ),
        migrations.AlterField(
            model_name='contactconfiguration',
            name='google_plus',
            field=models.CharField(blank=True, default='', help_text='Url (adres) do Google+', max_length=200),
        ),
        migrations.AlterField(
            model_name='contactconfiguration',
            name='instagram',
            field=models.CharField(blank=True, default='', help_text='Url (adres) do Instagrama', max_length=200),
        ),
        migrations.AlterField(
            model_name='contactconfiguration',
            name='linkedin',
            field=models.CharField(blank=True, default='', help_text='Url (adres) do LinkedIn', max_length=200),
        ),
        migrations.AlterField(
            model_name='contactconfiguration',
            name='snapchat',
            field=models.CharField(blank=True, default='', help_text='Url (adres) do Snapchat', max_length=200),
        ),
        migrations.AlterField(
            model_name='contactconfiguration',
            name='twitter',
            field=models.CharField(blank=True, default='', help_text='Url (adres) do twittera', max_length=200),
        ),
        migrations.AlterField(
            model_name='contactconfiguration',
            name='youtube',
            field=models.CharField(blank=True, default='', help_text='Url (adres) do YouTube', max_length=200),
        ),
    ]
