# Generated by Django 3.1.2 on 2020-12-13 03:08

from django.db import migrations, models
import djrichtextfield.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_auto_20201212_0351'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Zapisany kontakt do klienta', 'verbose_name_plural': 'Dane klientow'},
        ),
        migrations.AlterModelOptions(
            name='contactconfiguration',
            options={'verbose_name': 'Konfiguracja strony kontakt i informacji kontaktowych', 'verbose_name_plural': 'Konfiguracja strony kontakt i informacji kontaktowych'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=300, verbose_name='Email klienta'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(max_length=2000, verbose_name='Wiadomosc od klienta'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=400, verbose_name='Imie klienta'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=400, verbose_name='Telefon klienta'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Data modyfikacji'),
        ),
        migrations.AlterField(
            model_name='contactconfiguration',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Twoj email'),
        ),
        migrations.AlterField(
            model_name='contactconfiguration',
            name='facebook',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Url (adres) do facebooka'),
        ),
        migrations.AlterField(
            model_name='contactconfiguration',
            name='google_plus',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Url (adres) do Google+'),
        ),
        migrations.AlterField(
            model_name='contactconfiguration',
            name='have_questions',
            field=djrichtextfield.models.RichTextField(default='', verbose_name='Informacja nad formularzem "czy masz pytania?"'),
        ),
        migrations.AlterField(
            model_name='contactconfiguration',
            name='instagram',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Url (adres) do Instagrama'),
        ),
        migrations.AlterField(
            model_name='contactconfiguration',
            name='linkedin',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Url (adres) do LinkedIn'),
        ),
        migrations.AlterField(
            model_name='contactconfiguration',
            name='map_url',
            field=models.CharField(max_length=350, verbose_name='Url (adres) do mapy google'),
        ),
        migrations.AlterField(
            model_name='contactconfiguration',
            name='on_site_client_info',
            field=djrichtextfield.models.RichTextField(default='', verbose_name='Informacja o tym, ze dojezdzasz do klienta'),
        ),
        migrations.AlterField(
            model_name='contactconfiguration',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Bedzie on wyswietlany zarowno na stronie kontakt jak i w stopce', max_length=128, region=None, verbose_name='Twoj numer telefonu'),
        ),
        migrations.AlterField(
            model_name='contactconfiguration',
            name='snapchat',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Url (adres) do Snapchat'),
        ),
        migrations.AlterField(
            model_name='contactconfiguration',
            name='twitter',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Url (adres) do twittera'),
        ),
        migrations.AlterField(
            model_name='contactconfiguration',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Data modyfikacji'),
        ),
        migrations.AlterField(
            model_name='contactconfiguration',
            name='working_hours',
            field=djrichtextfield.models.RichTextField(verbose_name='Godziny pracy'),
        ),
        migrations.AlterField(
            model_name='contactconfiguration',
            name='youtube',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Url (adres) do YouTube'),
        ),
    ]
