# Generated by Django 3.1.2 on 2020-10-17 23:05

import datetime
from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_image', models.ImageField(help_text='Obrazek wyswietlany na gorze strony pod menu', upload_to='images/')),
                ('main_image_alt', models.CharField(help_text='Tekst wyświetlany w przypadku gdyby obrazek sie nie zaladowal', max_length=400)),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='modification date')),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(help_text='Glowny obrazek posta', upload_to='images/')),
                ('photo_alt', models.CharField(help_text='Tekst wyświetlany w przypadku gdyby obrazek sie nie zaladowal', max_length=400)),
                ('description', djrichtextfield.models.RichTextField(help_text='Glowny tekst posta')),
                ('publication_date', models.DateTimeField(default=datetime.datetime(2020, 10, 18, 1, 5, 50, 957219), help_text='Data publikacji posta')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='modification date')),
            ],
        ),
    ]
