# Generated by Django 3.1.2 on 2020-12-13 03:29

import datetime
from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_image', models.ImageField(upload_to='images/', verbose_name='Glowny obrazek')),
                ('main_image_alt', models.CharField(max_length=200, verbose_name='Nazwa')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Data modyfikacji')),
            ],
            options={
                'verbose_name': 'Konfiguracja bloga',
                'verbose_name_plural': 'Konfiguracja bloga',
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='images/', verbose_name='Glowny obrazek')),
                ('photo_alt', models.CharField(max_length=200, verbose_name='Nazwa')),
                ('description', djrichtextfield.models.RichTextField(verbose_name='Glowny tekst posta')),
                ('publication_date', models.DateTimeField(default=datetime.datetime(2020, 12, 13, 4, 29, 49, 973366), verbose_name='Data publikacji posta')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Data modyfikacji')),
                ('order', models.IntegerField(default=0, verbose_name='Kolejnosc')),
            ],
            options={
                'verbose_name': 'Post na bloga',
                'verbose_name_plural': 'Posty na bloga',
            },
        ),
    ]
