# Generated by Django 3.1.2 on 2020-12-27 04:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='publication_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 27, 5, 6, 13, 91619), verbose_name='Data publikacji posta'),
        ),
    ]
