# Generated by Django 3.1.2 on 2020-10-10 17:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='publication_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 10, 19, 8, 21, 596117), help_text='Data publikacji posta'),
        ),
    ]
