# Generated by Django 3.1.2 on 2020-10-10 17:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201010_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='publication_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 10, 19, 25, 2, 151445), help_text='Data publikacji posta'),
        ),
    ]
