# Generated by Django 3.1.2 on 2020-10-16 19:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201010_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='publication_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 16, 21, 6, 4, 9249), help_text='Data publikacji posta'),
        ),
    ]
