# Generated by Django 3.1.2 on 2020-10-17 13:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20201016_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='publication_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 17, 15, 26, 35, 280092), help_text='Data publikacji posta'),
        ),
    ]
