# Generated by Django 3.1.2 on 2020-10-20 18:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201018_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='publication_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 20, 20, 23, 18, 398969), help_text='Data publikacji posta'),
        ),
    ]
