# Generated by Django 3.1.2 on 2020-10-17 13:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201017_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='publication_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 17, 15, 28, 20, 987434), help_text='Data publikacji posta'),
        ),
    ]
