# Generated by Django 3.1.2 on 2020-11-12 02:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20201020_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='publication_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 12, 3, 53, 31, 885829), help_text='Data publikacji posta'),
        ),
    ]
