# Generated by Django 2.2.17 on 2020-11-17 23:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20201112_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='publication_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 17, 23, 30, 57, 670735), help_text='Data publikacji posta'),
        ),
    ]
