# Generated by Django 3.1.2 on 2020-11-23 20:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20201117_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='publication_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 23, 21, 10, 49, 868940), help_text='Data publikacji posta'),
        ),
    ]
