# Generated by Django 3.1.2 on 2020-11-23 20:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20201123_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='publication_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 23, 21, 37, 17, 247169), help_text='Data publikacji posta'),
        ),
    ]
