# Generated by Django 3.1.2 on 2020-12-12 02:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20201123_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='publication_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 12, 3, 9, 51, 468319), help_text='Data publikacji posta'),
        ),
    ]
