# Generated by Django 3.1.2 on 2020-12-12 02:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20201212_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='publication_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 12, 3, 51, 49, 311691), help_text='Data publikacji posta'),
        ),
    ]
