# Generated by Django 3.1.2 on 2020-12-13 01:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20201212_0351'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blogconfiguration',
            name='main_image_alt',
            field=models.CharField(help_text='Tekst wyświetlany w przypadku gdyby obrazek sie nie zaladowal', max_length=200),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='photo_alt',
            field=models.CharField(help_text='Tekst wyświetlany w przypadku gdyby obrazek sie nie zaladowal', max_length=200),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='publication_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 13, 2, 58, 41, 52081), help_text='Data publikacji posta'),
        ),
    ]
