# Generated by Django 3.1.2 on 2020-12-13 03:08

import datetime
from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20201213_0258'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogconfiguration',
            options={'verbose_name': 'Konfiguracja bloga', 'verbose_name_plural': 'Konfiguracja bloga'},
        ),
        migrations.AlterModelOptions(
            name='blogpost',
            options={'verbose_name': 'Post na bloga', 'verbose_name_plural': 'Posty na bloga'},
        ),
        migrations.AlterField(
            model_name='blogconfiguration',
            name='main_image',
            field=models.ImageField(upload_to='images/', verbose_name='Glowny obrazek'),
        ),
        migrations.AlterField(
            model_name='blogconfiguration',
            name='main_image_alt',
            field=models.CharField(max_length=200, verbose_name='Nazwa'),
        ),
        migrations.AlterField(
            model_name='blogconfiguration',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Data modyfikacji'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='description',
            field=djrichtextfield.models.RichTextField(verbose_name='Glowny tekst posta'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Kolejnosc'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='photo',
            field=models.ImageField(upload_to='images/', verbose_name='Glowny obrazek'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='photo_alt',
            field=models.CharField(max_length=200, verbose_name='Nazwa'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='publication_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 13, 4, 8, 39, 999363), verbose_name='Data publikacji posta'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Data modyfikacji'),
        ),
    ]
