# Generated by Django 3.1.2 on 2020-12-13 03:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20201213_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='publication_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 13, 4, 10, 53, 88782), verbose_name='Data publikacji posta'),
        ),
    ]
