# Generated by Django 3.1.1 on 2020-09-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=3000)),
                ('email', models.EmailField(max_length=300)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
    ]
