# Generated by Django 3.1.2 on 2020-10-07 15:35

import django.core.validators
from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_text', models.CharField(max_length=400)),
                ('image', models.ImageField(upload_to='images/')),
                ('image_alt', models.CharField(max_length=400)),
                ('description', djrichtextfield.models.RichTextField()),
                ('visible', models.BooleanField(default=False)),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='SliderConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_image_time_ms', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(10000)])),
            ],
        ),
        migrations.CreateModel(
            name='SliderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('image_alt', models.CharField(max_length=400)),
                ('visible', models.BooleanField(default=False)),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='date published')),
            ],
        ),
    ]
