# Generated by Django 3.2 on 2021-05-21 21:58

import django.core.validators
from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainBoxItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_text', models.CharField(max_length=400, verbose_name='Tekst naglowka')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Obrazek')),
                ('image_alt', models.CharField(max_length=200, verbose_name='Nazwa')),
                ('description', djrichtextfield.models.RichTextField(verbose_name='Opis')),
                ('visible', models.BooleanField(default=False, verbose_name='Zaznacz jesli element ma byc widoczny i nie pomijany')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Data modyfikacji')),
                ('element_order', models.IntegerField(default=0, verbose_name='Kolejnosc')),
            ],
            options={
                'verbose_name': 'Box / karta',
                'verbose_name_plural': 'Karty/boxy na stronie glownej',
            },
        ),
        migrations.CreateModel(
            name='MainConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_modal_visible', models.BooleanField(default=False, verbose_name='Czy dialog newsletter ma sie wyswietlac?')),
                ('newsletter_info', djrichtextfield.models.RichTextField(verbose_name='Naglowek newslettera')),
                ('main_text', djrichtextfield.models.RichTextField(verbose_name='Tekst w newsletterze')),
                ('permission_text', models.TextField(default='Wyrażam zgodę na przetwarzanie podanych powyżej danych w celu otrzymywania newslettera. Wyrażam zgodę na przesyłanie na mój adres e-mail informacji o nowościach, promocjach, produktach i usługach od firmy Justyna Pietraszek Mobilne Centrum Masażu Relaksownia. Zapoznałem się z Polityką Prywatności.', verbose_name='Tresc zgody klienta na przesylanie newslettera')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Data modyfikacji')),
            ],
            options={
                'verbose_name': 'Konfiguracja strony glownej i newslettera',
                'verbose_name_plural': 'Konfiguracja strony glownej i newslettera',
            },
        ),
        migrations.CreateModel(
            name='MainSliderConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_image_time_ms', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(10000)], verbose_name='Czas po ktorym zmieni sie obrazek w sliderze')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Data modyfikacji')),
            ],
            options={
                'verbose_name': 'Konfiguracja slidera na stronie glownej',
                'verbose_name_plural': 'Konfiguracja slidera na stronie glownej',
            },
        ),
        migrations.CreateModel(
            name='MainSliderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Obrazek')),
                ('image_alt', models.CharField(max_length=200, verbose_name='Nazwa')),
                ('visible', models.BooleanField(default=False, verbose_name='Zaznacz jesli element ma byc widoczny i nie pomijany')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Data modyfikacji')),
                ('element_order', models.IntegerField(default=0, verbose_name='Kolejnosc')),
            ],
            options={
                'verbose_name': 'Element slidera',
                'verbose_name_plural': 'Elementy slidera',
            },
        ),
    ]
