# Generated by Django 3.1.2 on 2020-11-23 20:37

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainconfiguration',
            name='main_text',
            field=djrichtextfield.models.RichTextField(default=''),
            preserve_default=False,
        ),
    ]
