# Generated by Django 3.2 on 2021-04-21 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainconfiguration',
            name='permission_text',
            field=models.TextField(default='Wyrażam zgodę na przetwarzanie podanych powyżej danych w celu otrzymywania newslettera. Wyrażam zgodę na przesyłanie na mój adres e-mail informacji o nowościach, promocjach, produktach i usługach od firmy Justyna Pietraszek Mobilne Centrum Masażu Relaksownia. Zapoznałem się z Polityką Prywatności.', verbose_name='Tresc zgody klienta na przesylanie newslettera'),
        ),
    ]
