# Generated by Django 3.1.2 on 2020-10-01 18:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='containeritem',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='slideritem',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='containeritem',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='date published'),
        ),
        migrations.AddField(
            model_name='info',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='date published'),
        ),
        migrations.AddField(
            model_name='slideritem',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='date published'),
        ),
    ]
