# Generated by Django 3.1.2 on 2020-12-13 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_mainconfiguration_box_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainboxitem',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mainslideritem',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mainboxitem',
            name='image_alt',
            field=models.CharField(help_text='Tekst wyświetlany w przypadku gdyby obrazek sie nie zaladowal', max_length=200),
        ),
        migrations.AlterField(
            model_name='mainslideritem',
            name='image_alt',
            field=models.CharField(help_text='Tekst wyświetlany w przypadku gdyby obrazek sie nie zaladowal', max_length=200),
        ),
    ]
