# Generated by Django 3.1.2 on 2020-12-13 03:08

import django.core.validators
from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201213_0258'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainboxitem',
            options={'verbose_name': 'Box / karta', 'verbose_name_plural': 'Karty/boxy na stronie glownej'},
        ),
        migrations.AlterModelOptions(
            name='mainconfiguration',
            options={'verbose_name': 'Konfiguracja strony glownej i newslettera', 'verbose_name_plural': 'Konfiguracja strony glownej i newslettera'},
        ),
        migrations.AlterModelOptions(
            name='mainsliderconfiguration',
            options={'verbose_name': 'Konfiguracja slidera na stronie glownej', 'verbose_name_plural': 'Konfiguracja slidera na stronie glownej'},
        ),
        migrations.AlterModelOptions(
            name='mainslideritem',
            options={'verbose_name': 'Element slidera', 'verbose_name_plural': 'Elementy slidera'},
        ),
        migrations.AlterField(
            model_name='mainboxitem',
            name='description',
            field=djrichtextfield.models.RichTextField(verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='mainboxitem',
            name='header_text',
            field=models.CharField(max_length=400, verbose_name='Tekst naglowka'),
        ),
        migrations.AlterField(
            model_name='mainboxitem',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='Obrazek'),
        ),
        migrations.AlterField(
            model_name='mainboxitem',
            name='image_alt',
            field=models.CharField(max_length=200, verbose_name='Nazwa'),
        ),
        migrations.AlterField(
            model_name='mainboxitem',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Kolejnosc'),
        ),
        migrations.AlterField(
            model_name='mainboxitem',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Data modyfikacji'),
        ),
        migrations.AlterField(
            model_name='mainboxitem',
            name='visible',
            field=models.BooleanField(default=False, verbose_name='Zaznacz jesli element ma byc widoczny i nie pomijany'),
        ),
        migrations.AlterField(
            model_name='mainconfiguration',
            name='is_modal_visible',
            field=models.BooleanField(default=False, verbose_name='Czy dialog newsletter ma sie wyswietlac?'),
        ),
        migrations.AlterField(
            model_name='mainconfiguration',
            name='main_text',
            field=djrichtextfield.models.RichTextField(verbose_name='Tekst w newsletterze'),
        ),
        migrations.AlterField(
            model_name='mainconfiguration',
            name='newsletter_info',
            field=djrichtextfield.models.RichTextField(verbose_name='Naglowek newslettera'),
        ),
        migrations.AlterField(
            model_name='mainconfiguration',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Data modyfikacji'),
        ),
        migrations.AlterField(
            model_name='mainsliderconfiguration',
            name='change_image_time_ms',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(10000)], verbose_name='Czas po ktorym zmieni sie obrazek w sliderze'),
        ),
        migrations.AlterField(
            model_name='mainsliderconfiguration',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Data modyfikacji'),
        ),
        migrations.AlterField(
            model_name='mainslideritem',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='Obrazek'),
        ),
        migrations.AlterField(
            model_name='mainslideritem',
            name='image_alt',
            field=models.CharField(max_length=200, verbose_name='Nazwa'),
        ),
        migrations.AlterField(
            model_name='mainslideritem',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Kolejnosc'),
        ),
        migrations.AlterField(
            model_name='mainslideritem',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Data modyfikacji'),
        ),
        migrations.AlterField(
            model_name='mainslideritem',
            name='visible',
            field=models.BooleanField(default=False, verbose_name='Zaznacz jesli element ma byc widoczny i nie pomijany'),
        ),
    ]
