# Generated by Django 3.1.1 on 2020-09-19 20:47

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqitem',
            name='answer_text',
            field=djrichtextfield.models.RichTextField(),
        ),
        migrations.AlterField(
            model_name='faqitem',
            name='question_text',
            field=djrichtextfield.models.RichTextField(),
        ),
    ]
