# Generated by Django 3.1.2 on 2020-12-13 20:50

from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='images/', verbose_name='Twoje glowne zdjecie')),
                ('photo_alt', models.CharField(max_length=200, verbose_name='Alternatywny tekst przy braku zdjecia')),
                ('description', djrichtextfield.models.RichTextField(verbose_name='Opis')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Data modyfikacji')),
            ],
            options={
                'verbose_name': 'Informacja o Tobie',
                'verbose_name_plural': 'Informacja o Tobie',
            },
        ),
    ]
