# Generated by Django 3.2 on 2021-05-21 21:58

from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CertItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Zdjecie certyfikatu')),
                ('image_alt', models.CharField(max_length=100, verbose_name='Nazwa certyfikatu')),
                ('element_order', models.IntegerField(default=0, verbose_name='Kolejnosc')),
            ],
            options={
                'verbose_name': 'Certyfikat',
                'verbose_name_plural': 'Certyfikaty',
            },
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='images/', verbose_name='Twoje glowne zdjecie')),
                ('photo_alt', models.CharField(max_length=200, verbose_name='Alternatywny tekst przy braku zdjecia')),
                ('description', djrichtextfield.models.RichTextField(verbose_name='Opis')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Data modyfikacji')),
            ],
            options={
                'verbose_name': 'Informacja o Tobie',
                'verbose_name_plural': 'Informacja o Tobie',
            },
        ),
    ]
