# Generated by Django 3.1.2 on 2020-12-13 03:08

from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_auto_20201213_0258'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='info',
            options={'verbose_name': 'Informacja o Tobie', 'verbose_name_plural': 'Informacja o Tobie'},
        ),
        migrations.AlterField(
            model_name='info',
            name='description',
            field=djrichtextfield.models.RichTextField(verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='info',
            name='photo',
            field=models.ImageField(upload_to='images/', verbose_name='Twoje glowne zdjecie'),
        ),
        migrations.AlterField(
            model_name='info',
            name='photo_alt',
            field=models.CharField(max_length=200, verbose_name='Alternatywny tekst przy braku zdjecia'),
        ),
        migrations.AlterField(
            model_name='info',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Data modyfikacji'),
        ),
    ]
