# Generated by Django 3.2 on 2021-05-21 21:58

from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privacy_text', djrichtextfield.models.RichTextField(blank=True, verbose_name='Tekst polityki prywatnosci')),
                ('order_rules', djrichtextfield.models.RichTextField(blank=True, verbose_name='Tekst zasad zamowien')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Data ostatniej modyfikacji')),
            ],
            options={
                'verbose_name': 'Konfiguracja polityk',
                'verbose_name_plural': 'Konfiguracja polityk',
            },
        ),
    ]
