# Generated by Django 3.1.5 on 2021-01-28 11:19

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policyconfiguration',
            name='order_rules',
            field=djrichtextfield.models.RichTextField(blank=True, verbose_name='Tekst zasad zamowien'),
        ),
        migrations.AlterField(
            model_name='policyconfiguration',
            name='privacy_text',
            field=djrichtextfield.models.RichTextField(blank=True, verbose_name='Tekst polityki prywatnosci'),
        ),
    ]
