# Generated by Django 3.1.1 on 2020-09-19 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containeritem',
            name='image',
            field=models.ImageField(upload_to='main/static'),
        ),
        migrations.AlterField(
            model_name='slideritem',
            name='image',
            field=models.ImageField(upload_to='main/static'),
        ),
    ]
