# Generated by Django 3.1.1 on 2020-09-19 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='images/')),
                ('photo_alternate_text', models.CharField(max_length=3000)),
                ('description', models.CharField(max_length=3000)),
            ],
        ),
    ]
