# Generated by Django 3.1.1 on 2020-09-15 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='containeritem',
            name='header_text',
            field=models.CharField(default='Relaks', max_length=3000),
        ),
    ]
