# Generated by Django 3.1.1 on 2020-09-19 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200919_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containeritem',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='slideritem',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
